name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: src/frontend
      run: docker build -t gatherorg-frontend:latest .

    - name: Login to GitHub Container Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/gatherorg-frontend:latest

  ## TODO
      # deploy:
  #   runs-on: ubuntu-latest
  #   needs: dockerize

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Deploy to Kubernetes
  #     env:
  #       KUBECONFIG: ${{ secrets.KUBECONFIG }}
  #     run: |
  #       kubectl set image deployment/frontend frontend=gatherorg-frontend:latest
